### ISSUE TITLE
I can't disable Mangohud to open in every app after use GOverlay once

### ISSUE THREAD

**Issue by fagnerln** [benjamimgois/goverlay#43]
I clicked on Global Enable, and I can't unset anymore, I click on it, it shows a notification saying that it's disabled and to restart to take effect, I restarted the PC and MangoHUD is still enabled to every application, if I open GOverlay, it's enabled again.

**Comment by benjamimgois** [comment]
Hey @fagnerln , sorry for my late. I was in hospital due to covid19, i'm getting things back to normal now. I think i know what cause the problem, will keep that in my todo list. Thanks for reporting.

**Comment by fagnerln** [comment]
Wow, what a difficult time we are living, good to know that you are better now.

I just deleted the .profile (iirc) file on my home, which is a workaround for now, maybe just need to search in the file and delete the line.

God bless you!

**Comment by benjamimgois** [comment]
@fagnerln i just made some changes on 0.3.6, i think the problem is solved. Thanks for the report man.

**Comment by fagnerln** [comment]
The bug persists... 
What this option do? I'm not a dev but I noticed that it changes the .profile on home with "export MANGOHUD=1", I just deleted the line and it's fix

**Comment by benjamimgois** [comment]
@fagnerln this option basically creates a backup file of your ".profile" as "`.profile.bkp` and adds the export MANGOHUD=1 line. When you disable the Global enable option it deletes the `.profile` file and renames the backup file as the official one.

**Comment by leucome** [comment]
Maybe there could be a script who look for the presence MANGOHUD=1.   For some reason I ended up with multiple line of MANGOHUD=1   and  the .bkp also contained multiple line of MANGOHUD=1.  

My guess is that at some point it think the global option is off when it's already ON. So it make a back up with the option turned on and add a redundant  line. Each time it happens an additional  MANGOHUD=1 is added.

**Comment by benjamimgois** [comment]
Yeah... the current implementation of global enable isn't the best. I'll add it to the (growing) todo list :)  

Thanks for the reporting @fagnerln  and @leucome

**Comment by Caliel666** [comment]
sorry to revive a old issue, i was having the same problem, but i fixed it by creating a empty .profile.bkp file and switching global enable to off, i think the issue happened because i didn't have a .profile before so it never created the backup, since the global switch is based on those files, that caused the bug, i hope this helps

**Comment by fakhraldin** [comment]
Salam wa Shalom Benjamin, best wishes for your recovery. Hopefully you are ok.
About the bug: I installed goverlay on fedora and i am using Lutris. And once i activated "Global Enable" in the goverlay menu, the activation persisted even after advised restarts. I deleted goverlay and searched all places for conifg files and deleted them.
/home/username/.config/goverlay
/home/username/.config/MangoHud/
That did not help. There seem to be a lot of config places for mangohud, which might cross and interfere each other, i guess. But i made sure, that global enable was not active in lutris or on any individual app. 

Finally I only was able to make the HUD disappear by deleting following files. Of course this is not an optimal solution.
/usr/share/vulkan/implicit_layer.d/MangoHud.json
/usr/share/vulkan/implicit_layer.d/vkBasalt.json
Renaming them for deactivation is also possible. Maybe this insight can serve as another piece to solve the puzzle.

**Comment by fagnerln** [comment]
> Salam wa Shalom Benjamin, best wishes for your recovery. Hopefully you are ok.
> About the bug: I installed goverlay on fedora and i am using Lutris. And once i activated "Global Enable" in the goverlay menu, the activation persisted even after advised restarts. I deleted goverlay and searched all places for conifg files and deleted them.
> /home/username/.config/goverlay
> /home/username/.config/MangoHud/
> That did not help. There seem to be a lot of config places for mangohud, which might cross and interfere each other, i guess. But i made sure, that global enable was not active in lutris or on any individual app.
> 
> Finally I only was able to make the HUD disappear by deleting following files. Of course this is not an optimal solution.
> /usr/share/vulkan/implicit_layer.d/MangoHud.json
> /usr/share/vulkan/implicit_layer.d/vkBasalt.json
> Renaming them for deactivation is also possible. Maybe this insight can serve as another piece to solve the puzzle.

~/.profile?
