### ISSUE TITLE
MangoHud enforcing anisotropic filtering that is not possible to disable.

### ISSUE THREAD

**Issue by Tecnio** [benjamimgois/goverlay#83]
GOverlay 1.0 has the feature to set anisotropic filtering to force a specific value, while this feature is very useful it cannot be disabled. The default 0 value does not disable the feature but disable anisotropic filtering for all MangoHud applications causing weird texture issues at angles. Removing the value from the config fixes the problem.

Version: GOverlay 1.0
System: Arch Linux with KDE Plasma

Steps to Reproduce:
1. Install GOverlay 
2. Hit the "Save" button

**Comment by benjamimgois** [comment]
Thanks for reporting @Tecnio . I'll work in a fix for next update

**Comment by benjamimgois** [comment]
@Tecnio Fixed in latest 1.1 release

**Comment by benjamimgois** [comment]
fixed in 1.1 release

**Comment by HalJordan** [comment]
What was the fix for this specifically? I'm still showing issues where having mangohud enabled breaks textures on Baldur's Gate 3 specifically. I'm not seeing it with anything else.

**Comment by benjamimgois** [comment]
Before 1.1, if you set anisotropic filtering to zero it would still write `af=0` in the config file. After 1.1 there will be no af setting on config file.

**Comment by HalJordan** [comment]
Yeah I have to either disable my, or disable filtering on the performance
tab. Not sure why mh would need to touch that since most any game will have
it.
